import './globals.css'
import type { Metadata } from 'next'
import { Raleway, WindSong } from 'next/font/google'
import Navigation from './components/Navigation';

const raleway = Raleway({
    subsets: ["latin"],
    weight: ["100", "400"],
    display: "swap",
    variable: "--font-raleway",
});
const windsong = WindSong({
  subsets: ["latin"],
    weight: "400",
    display: "swap",
    variable: "--font-windsong",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${windsong.variable}`}>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
